renamed this.domain to this.pbxDomain in webRTC module to fix issue with node
overriding the variable `domain` in the context, causes node to believe you are using a legacy node.js domain instance, and tries to execute the .enter method, causing `TypeError: domain.enter is not a function`.   This commit fixes that